name: Deploy to EC2 Instances

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: Staging

    runs-on: ubuntu-latest
    env:
      BASTION_HOST_PRIVATE_KEY: ${{ secrets.BASTION_HOST_PRIVATE_KEY }}
      MONGO_AUTH_CREDENTIALS: ${{ secrets.MONGO_AUTH_CREDENTIALS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name:  Run Deployment Script
      run: |
        bash deployment/runOnGithubAction.sh
      env:
        BASTION_HOST_PRIVATE_KEY: ${{ secrets.STAGING_BASTION_HOST_PRIVATE_KEY }}
        MONGO_AUTH_CREDENTIALS: ${{ secrets.MONGO_AUTH_CREDENTIALS }}
        BRANCH_NAME_TO_DEPLOY: ${{ steps.extract_branch.outputs.branch }}
        BASTION_HOST_INSTANCE_NAME: "staging-QB-Bastion-Host"
        TARGET_GROUP_NAME: "staging-QB-lb-alb-tg"
        ENVIRONMENT_PREFIX: "staging-QB-"
        LOGS_S3_BUCKET: "staging-qb-ec2-logs"